spring.datasource.url=jdbc:postgresql://localhost:5432/LMS
spring.datasource.username=postgres
spring.datasource.password=2005@Pranav
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Needed for SPA forward mapping pattern compatibility
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
