spring.application.name=LMS
spring.datasource.url= //Your DB
 spring.datasource.username=// your db username
 spring.datasource.password=//  your db password
 spring.jpa.hibernate.ddl-auto=update
 spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
